### ISSUE TITLE
Not updating title

### ISSUE THREAD

**Issue by Gourav1910** [conorzhong/obsidian-auto-front-matter#1]
HI I tested your plugin and yes it is updating modification time but not updating title. I even closed and reopened the note and still the title is not updated. Even after running the command to update it manually then also it doesn't update it.
![image](https://github.com/conorzhong/obsidian-auto-front-matter/assets/101202140/bc194fcc-4f08-40c5-b602-8a76fc91e2ef)

**Comment by conorzhong** [comment]
Currently, the title comes from the same as the filename, did your filename change?
