### ISSUE TITLE
More discretionality needed

### ISSUE THREAD

**Issue by Canna71** [conorzhong/obsidian-auto-front-matter#3]
Hi, I was about to develop a similar plugin when I encountered yours. In order to be more useful, I would consider the following changes:
- if the front matter is created on an existing note, `datetimeCreate` should be the `ctime` of the file
- user should be able to decide which property to set
- tag names should be configurable too

Please tell me if it is on the roadmap or I should work on a PR

**Comment by conorzhong** [comment]
1. "user should be able to decide which property to set" is on roadmap. But PR welcome😄.
2. "`ctime` of the file" maybe not reliable in vault(maybe sync, git, .etc), I remember that I have read some issues in obsidian's forum.

**Comment by Canna71** [comment]
Yes, the fact that Obsidian Sync does not keep the original creation date is the actual reason why I need those fields in the first place :-)
But I am talking about adding the creation date attribute to an already existing page: in this case you have two choices IMHO:
- you avoid setting the creation date for the simple reason that you cannot be 100% sure about it
- you put the `ctime` which at least **could** be the creation date. Or at least it will be before the `mtime`; as it is right now you are claiming that the note was created when you add the auto frontmatter to it, which seems worse to me. Consider that not all Obsidian users are using Sync, and for most of those reading `ctime` is exact.

I feel the second choice is OK for the most cases, or at least it could be an option.

**Comment by conorzhong** [comment]
Yes, we can add `ctime` as default, if there is no  `datetimeCreate`
