### ISSUE TITLE
FR: Custom field

### ISSUE THREAD

**Issue by XinYun2020** [conorzhong/obsidian-auto-front-matter#5]
### What?

- It would be great if can add custom front matter keys automatically when file changes/ when file save

### Why?

My potential use case for the plugin 
- Automatically add `lastModifier: Alice` when saving a file. In the future, with other plugins like **Chronology**, I might be able to input the `lastModifier` name and check the file modification/creation history timeline for a specific modifier. 
- This would be helpful for visualizing collaboration on Obsidian files and being able to see the timeline of modifications made by different authors (`lastModifiers`). 
- Currently, **Chronology** uses `datetimeUpdate `to create the timeline, but it does not have a feature to select the author option. This is just a thought for a "Great to have" feature.

### Other note

- Linter Plugin  is able to set custom order of the front matters (this plugin can work perfectly with Linter Plugin)
in Linter Plugin if you want the order of title, id, datetimeCreate, datetimeUpdate. You can input below to the field (YAML Key Priority Sort Order):

```plaintext
title:
id:
datetimeCreate:
datetimeUpdate:
```

**Comment by conorzhong** [comment]
谢谢！所以我认为我的工作有：
1. 可以考虑删除自动排序的功能，兼容 Linter Plugin
2. 可以考虑支持自定义键值
---
Thank you! So I think my tasks are:
1. Consider removing the automatic sorting feature to be compatible with the Linter Plugin.
2. Consider supporting custom key-value pairs.

**Comment by conorzhong** [comment]
看起来 Linter 插件有时间戳功能（创建日期、修改日期）和标题功能。同样功能在本插件中不是必须的，可以考虑去除

只保留`id`的功能感觉就足够了，这也是这个插件的初衷

---

It seems that the Linter plugin has a timestamp feature (creation date, modification date) and a title feature. The same features are not necessary in this plugin and can be considered for removal.

Keeping only the `id` feature seems to be enough, which is also the original intention of this plugin.

**Comment by conorzhong** [comment]
考虑把`id`的逻辑也放在自定义键值对里面，这样功能更完善

---

Consider putting the logic of `id` in the custom key-value pairs as well, making the functionality more comprehensive.

**Comment by XinYun2020** [comment]
There is another use case I have for the custom field.

### Context

For instance, I am in the process of reviewing a course. In the front matter, I have a field named `course:` to help me identify which course a topic or concept was mentioned previously. This is also useful when I use the **Dataview Plugin** to extract a summary table of concepts I've learned in this course.

Here is an example of the dataview query I would use to extract the course concept summary table:
````
```dataview 
TABLE WITHOUT ID 
         file.link AS "Related Concept for the Exam",
	description,
	highlights
FROM ""
WHERE contains(file.frontmatter.course, this.file.name)
SORT file.name ASC
```
````

### The Use Case

The custom field feature can assist me in the following scenario:

- After editing the plugin settings with a custom key: `course` and value: `"[[MAST90083]]"` (where MAST90083 is the course page name)
- When I am focusing on the review process, and all the content I open is related to a `course` I want the front matter to be automatically updated when I save the file.
- When saving:
- If the `course` does not exist, then add `course` with `"[[MAST90083]]"` as an `array` item in YAML.
- If the `course` already exists in the current YAML, change the current `course` items to an array and append a new line: `- "[[MAST90083]]"`
- It would also be great if there were a command palette command to toggle the auto front matter mode.
