### ISSUE TITLE
FR: Auto "Auto Front Matter: Update current front matter" when "Save current file" Hotkey pressed with Cmd+S

### ISSUE THREAD

**Issue by xinyun2020** [conorzhong/obsidian-auto-front-matter#9]
is it possible to trigger the "Auto Front Matter: Update current front matter" when the "Save current file" Hotkey is pressed with Cmd+S

or have another boolean attribute for each field, e.g. **Update When Save: [ ]**

so that the field will perform the action type when CMD+S (save current file)

(the UI and the new feature look (ﾉ^_^)ﾉ so great!  Thank you for all the hard work, that is one of my favorite plugging now)

**Comment by conorzhong** [comment]
You can use Commander plugin
![image](https://github.com/conorzhong/obsidian-auto-front-matter/assets/39456642/ad21da39-9002-4f7b-bc98-daa67bfc230a)

Add two command: such as "Update current front matter" and "Save current file"
![image](https://github.com/conorzhong/obsidian-auto-front-matter/assets/39456642/ee7dda03-ae54-4188-a2b9-b8ca6cc87e2a)

Save

Then at hotkeys, add ctrl + s at "Commander: Save File with Auto Front Matter
![image](https://github.com/conorzhong/obsidian-auto-front-matter/assets/39456642/6a861b79-0ade-474b-8e26-82b553e89847)

There might be a conflict: you can delete original "Save current file" hotkey

At last
![image](https://github.com/conorzhong/obsidian-auto-front-matter/assets/39456642/50098ac7-7aac-46a7-82df-05b9f7368f24)

**Comment by conorzhong** [comment]
Seems like that obsidian plugin api doesn't support us to directly add "ctrl + s" feature, support this may need lots of hack code.

**Comment by xinyun2020** [comment]
Thanks for the clear explanation. ❤️
